/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc6551AccountSol from "./ERC6551Account.sol";
export type { erc6551AccountSol };
export type { ERC6551Registry } from "./ERC6551Registry";
export type { Pengumon } from "./Pengumon";
export type { Soul } from "./Soul";
