/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Pengumon__factory } from "./Pengumon__factory";
export { TestNFT__factory } from "./TestNFT__factory";
